In [19]:
#just testing that libraries were installed properly 
import numpy as np
import pandas as pd
import matplotlib
import sklearn

# Test numpy
print("NumPy version:", np.__version__)
arr = np.array([1, 2, 3])
print("NumPy array:", arr)

# Test pandas
print("\nPandas version:", pd.__version__)
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print("Pandas DataFrame:")
print(df)

# Test matplotlib
print("\nMatplotlib version:", matplotlib.__version__)

# Test scikit-learn
print("\nScikit-learn version:", sklearn.__version__)


NumPy version: 1.26.4
NumPy array: [1 2 3]

Pandas version: 2.2.1
Pandas DataFrame:
   A  B
0  1  4
1  2  5
2  3  6

Matplotlib version: 3.8.3

Scikit-learn version: 1.4.1.post1


In [13]:
# #1. Create a rank 2 (2D) array that resembles the matrix below.
# [[11 12 13 14]
#  [15 16 17 18]]
import numpy as np # import np 
print ("hello world ") # test working python
twoDarray = np.array([[11,12,13,14],[15,16,17,18]])
print(twoDarray)

hello world 
[[11 12 13 14]
 [15 16 17 18]]


In [18]:
# Use the appropriate functions to solve the following questions
# 1. Create an array with 4 rows and 3 columns of zeros. Your results should look as below:
# [[0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]

import numpy as numPy #import numpy
arr = numPy.zeros((4,3)) # first number rows, second collumns
print (arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# 2.Create an array of ones that has 3 rows and 4 columns. Your results should look as below:
# [[1. 1. 1. 1.]
# [1. 1. 1. 1.]
# [1. 1. 1. 1.]]
import numpy as NumPy

arr = NumPy.ones((3,4)) #same as zeros just put ones
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
# # 3. Create an array containing integers 4 to 13 inclusive. Your results should look as below:
# # [4 5 6 7 8 9 10 11 12 13]
import numpy as NumPy
# #since the numbers follow a pattern of adding 1 
# #you can just use the arrange comamnd from numPy

arr1 = NumPy.arange(4,14) #starting index, n+1
print(arr1)



[ 4  5  6  7  8  9 10 11 12 13]


In [ ]:
# 4. Create an array containing
# [0., 1.5, 3., 4.5]

In [ ]:
# 5. Create a 2 by 2 array containing '4' in each position. Your results should look like this:
# [[4 4]
#  [4 4]]

In [ ]:

# 6
# . Create 2 matrices:

# i. Identity matrix of size 4
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]
# ii. Diagonal matrix with [10,12] as the diagonals
# [[10  0]
#  [ 0 12]]

In [ ]:
# 7. Create a 3 by 3 array with random floats in [0, 10]. Your answer may be different because it is random but it should look something like this:
# [[6.3685612  0.61720883 8.93157783]
#  [3.69927617 5.79879583 7.62145626]
#  [7.21895112 4.02011535 4.48844787]]

In [ ]:
# 8. Create a 3 by 3 array with random integers in [10, 20]. Your answer may be different because it is random but it should look something like this:
# [[19 11 13]
#  [10 11 13]
#  [11 14 10]]


In [ ]:
# SLICING ARRAYS

# 1. Use this array for the following practice:
# myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])

# a. Get a subarray of the first row and first 2 columns. Your results should look like this:
# [11 12]

# b. Change all elements in 1st and second row to 0. Your results should look like this:
# [[ 0  0  0]
#  [ 0  0  0]
#  [17 18 19]]