In [13]:
# #1. Create a rank 2 (2D) array that resembles the matrix below.
# [[11 12 13 14]
#  [15 16 17 18]]
import numpy as np # import np 
print ("hello world ") # test working python
twoDarray = np.array([[11,12,13,14],[15,16,17,18]])
print(twoDarray)

hello world 
[[11 12 13 14]
 [15 16 17 18]]


In [14]:

!{sys.executable} -m pip install numpy pandas scikit-learn matplotlib seaborn jupyter




  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress t

In [17]:

import numpy as np
import pandas as pd
import matplotlib
import sklearn

# Test numpy
print("NumPy version:", np.__version__)
arr = np.array([1, 2, 3])
print("NumPy array:", arr)

# Test pandas
print("\nPandas version:", pd.__version__)
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print("Pandas DataFrame:")
print(df)

# Test matplotlib
print("\nMatplotlib version:", matplotlib.__version__)

# Test scikit-learn
print("\nScikit-learn version:", sklearn.__version__)


NumPy version: 1.26.4
NumPy array: [1 2 3]

Pandas version: 2.2.1
Pandas DataFrame:
   A  B
0  1  4
1  2  5
2  3  6

Matplotlib version: 3.8.3

Scikit-learn version: 1.4.1.post1
